export const siteUrl = "https://mbfassnacht.de";

export const person = {
  name: "Máximo Fassnacht",
  firstName: "Máximo",
  lastName: "Fassnacht",
  username: "mbfassnacht",
  email: "hello@fassnacht.dev",
  linkedin: "https://www.linkedin.com/in/mbfassnacht",
  github: "https://github.com/mbfassnacht",
  npm: "https://www.npmjs.com/~mbfassnacht",
};

// Gravatar identifies accounts by the SHA-256 of the lowercased, trimmed email:
//   printf '%s' "<email>" | tr '[:upper:]' '[:lower:]' | shasum -a 256
const gravatarHash =
  "f4991e211700999600c06b27ac15121317471665eed12dde880eb719072bff49";

export function gravatarUrl(size: number) {
  // d=404: fail the build instead of silently using a placeholder.
  return `https://gravatar.com/avatar/${gravatarHash}?s=${size}&d=404`;
}

// Downloaded from Gravatar at build time (src/app/avatar.png/route.ts) and
// served from this domain, so visitors never make requests to gravatar.com.
export const avatarPath = "/avatar.png";

export const siteTitle = `${person.name} | Engineering Manager & Staff Software Engineer`;

// Generated by src/app/og.png/route.tsx.
export const ogImage = {
  url: "/og.png",
  width: 1200,
  height: 630,
  alt: `${person.name} – Engineering Manager & Staff Software Engineer`,
};

const startWorking = new Date(2011, 3, 25);
const msPerYear = 365 * 24 * 60 * 60 * 1000;

// Computed at build time; the site is redeployed on every push.
export const workExperience = Math.floor(
  (Date.now() - startWorking.getTime()) / msPerYear,
);

export const siteDescription = `${person.name} – Engineering Manager and Staff Software Engineer at Taxfix with ${workExperience} years of experience in TypeScript, Node.js, Go, React, React Native, AWS, Kubernetes and production AI (LLM agents, MCP). Based in Germany.`;
